// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/about" | "/[locale]/admin" | "/[locale]/admin/[slug]" | "/[locale]/admin/[slug]/menu-import" | "/[locale]/admin/directory" | "/[locale]/admin/new" | "/[locale]/admin/requests" | "/[locale]/calculator" | "/[locale]/cities" | "/[locale]/cities/[city]" | "/[locale]/coming-soon" | "/[locale]/contact" | "/[locale]/dashboard" | "/[locale]/dashboard/[slug]" | "/[locale]/dashboard/[slug]/customers" | "/[locale]/dashboard/[slug]/marketing" | "/[locale]/dashboard/[slug]/menu" | "/[locale]/dashboard/[slug]/orders" | "/[locale]/dashboard/[slug]/orders/[orderId]" | "/[locale]/dashboard/[slug]/requests" | "/[locale]/dashboard/[slug]/settings" | "/[locale]/dashboard/[slug]/settings/billing" | "/[locale]/demo" | "/[locale]/eat" | "/[locale]/eat/[city]" | "/[locale]/eat/[city]/[listing]" | "/[locale]/grader" | "/[locale]/how-it-works" | "/[locale]/kitchen/[slug]" | "/[locale]/kitchen/[slug]/ticket/[orderId]" | "/[locale]/login" | "/[locale]/pricing" | "/[locale]/privacy" | "/[locale]/s/[slug]" | "/[locale]/s/[slug]/checkout" | "/[locale]/s/[slug]/order/[orderId]" | "/[locale]/stories" | "/[locale]/stories/[slug]" | "/[locale]/styleguide" | "/[locale]/terms"
type AppRouteHandlerRoutes = "/api/cron/automations" | "/api/cron/requests-digest" | "/api/cron/weekly-report" | "/api/dashboard/[slug]/customers.csv" | "/api/dashboard/[slug]/orders.csv" | "/api/eat/photo" | "/api/kitchen/[slug]/orders" | "/api/mobile/loyalty" | "/api/mobile/orders" | "/api/mobile/orders/[orderId]" | "/api/mobile/orders/[orderId]/confirm" | "/api/mobile/restaurants" | "/api/mobile/storefront/[slug]" | "/api/webhooks/stripe" | "/api/webhooks/twilio-sms" | "/llms.txt"
type PageRoutes = never
type LayoutRoutes = "/[locale]" | "/[locale]/admin" | "/[locale]/dashboard/[slug]" | "/[locale]/s/[slug]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/[locale]": { "locale": string; }
  "/[locale]/about": { "locale": string; }
  "/[locale]/admin": { "locale": string; }
  "/[locale]/admin/[slug]": { "locale": string; "slug": string; }
  "/[locale]/admin/[slug]/menu-import": { "locale": string; "slug": string; }
  "/[locale]/admin/directory": { "locale": string; }
  "/[locale]/admin/new": { "locale": string; }
  "/[locale]/admin/requests": { "locale": string; }
  "/[locale]/calculator": { "locale": string; }
  "/[locale]/cities": { "locale": string; }
  "/[locale]/cities/[city]": { "locale": string; "city": string; }
  "/[locale]/coming-soon": { "locale": string; }
  "/[locale]/contact": { "locale": string; }
  "/[locale]/dashboard": { "locale": string; }
  "/[locale]/dashboard/[slug]": { "locale": string; "slug": string; }
  "/[locale]/dashboard/[slug]/customers": { "locale": string; "slug": string; }
  "/[locale]/dashboard/[slug]/marketing": { "locale": string; "slug": string; }
  "/[locale]/dashboard/[slug]/menu": { "locale": string; "slug": string; }
  "/[locale]/dashboard/[slug]/orders": { "locale": string; "slug": string; }
  "/[locale]/dashboard/[slug]/orders/[orderId]": { "locale": string; "slug": string; "orderId": string; }
  "/[locale]/dashboard/[slug]/requests": { "locale": string; "slug": string; }
  "/[locale]/dashboard/[slug]/settings": { "locale": string; "slug": string; }
  "/[locale]/dashboard/[slug]/settings/billing": { "locale": string; "slug": string; }
  "/[locale]/demo": { "locale": string; }
  "/[locale]/eat": { "locale": string; }
  "/[locale]/eat/[city]": { "locale": string; "city": string; }
  "/[locale]/eat/[city]/[listing]": { "locale": string; "city": string; "listing": string; }
  "/[locale]/grader": { "locale": string; }
  "/[locale]/how-it-works": { "locale": string; }
  "/[locale]/kitchen/[slug]": { "locale": string; "slug": string; }
  "/[locale]/kitchen/[slug]/ticket/[orderId]": { "locale": string; "slug": string; "orderId": string; }
  "/[locale]/login": { "locale": string; }
  "/[locale]/pricing": { "locale": string; }
  "/[locale]/privacy": { "locale": string; }
  "/[locale]/s/[slug]": { "locale": string; "slug": string; }
  "/[locale]/s/[slug]/checkout": { "locale": string; "slug": string; }
  "/[locale]/s/[slug]/order/[orderId]": { "locale": string; "slug": string; "orderId": string; }
  "/[locale]/stories": { "locale": string; }
  "/[locale]/stories/[slug]": { "locale": string; "slug": string; }
  "/[locale]/styleguide": { "locale": string; }
  "/[locale]/terms": { "locale": string; }
  "/api/cron/automations": {}
  "/api/cron/requests-digest": {}
  "/api/cron/weekly-report": {}
  "/api/dashboard/[slug]/customers.csv": { "slug": string; }
  "/api/dashboard/[slug]/orders.csv": { "slug": string; }
  "/api/eat/photo": {}
  "/api/kitchen/[slug]/orders": { "slug": string; }
  "/api/mobile/loyalty": {}
  "/api/mobile/orders": {}
  "/api/mobile/orders/[orderId]": { "orderId": string; }
  "/api/mobile/orders/[orderId]/confirm": { "orderId": string; }
  "/api/mobile/restaurants": {}
  "/api/mobile/storefront/[slug]": { "slug": string; }
  "/api/webhooks/stripe": {}
  "/api/webhooks/twilio-sms": {}
  "/llms.txt": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/[locale]": never
  "/[locale]/admin": never
  "/[locale]/dashboard/[slug]": never
  "/[locale]/s/[slug]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
