// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[locale]/(admin)/admin/[slug]/menu-import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/[slug]/menu-import">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(admin)/admin/[slug]/menu-import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(admin)/admin/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(admin)/admin/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(admin)/admin/directory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/directory">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(admin)/admin/directory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(admin)/admin/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/new">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(admin)/admin/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(admin)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(admin)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(admin)/admin/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/requests">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(admin)/admin/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(dashboard)/dashboard/[slug]/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/[slug]/customers">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(dashboard)/dashboard/[slug]/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(dashboard)/dashboard/[slug]/marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/[slug]/marketing">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(dashboard)/dashboard/[slug]/marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(dashboard)/dashboard/[slug]/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/[slug]/menu">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(dashboard)/dashboard/[slug]/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(dashboard)/dashboard/[slug]/orders/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/[slug]/orders/[orderId]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(dashboard)/dashboard/[slug]/orders/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(dashboard)/dashboard/[slug]/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/[slug]/orders">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(dashboard)/dashboard/[slug]/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(dashboard)/dashboard/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(dashboard)/dashboard/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(dashboard)/dashboard/[slug]/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/[slug]/requests">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(dashboard)/dashboard/[slug]/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(dashboard)/dashboard/[slug]/settings/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/[slug]/settings/billing">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(dashboard)/dashboard/[slug]/settings/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(dashboard)/dashboard/[slug]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard/[slug]/settings">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(dashboard)/dashboard/[slug]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(dashboard)/kitchen/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/kitchen/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(dashboard)/kitchen/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(dashboard)/kitchen/[slug]/ticket/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/kitchen/[slug]/ticket/[orderId]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(dashboard)/kitchen/[slug]/ticket/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/about">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/calculator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/cities/[city]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cities/[city]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/cities/[city]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/cities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cities">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/cities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/contact">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/demo">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/eat/[city]/[listing]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/eat/[city]/[listing]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/eat/[city]/[listing]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/eat/[city]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/eat/[city]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/eat/[city]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/eat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/eat">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/eat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/grader/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/grader">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/grader/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/how-it-works/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/how-it-works">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/how-it-works/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/stories/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/stories/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/stories/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/stories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/stories">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/stories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/styleguide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/styleguide">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/styleguide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/terms">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/s/[slug]/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/s/[slug]/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/s/[slug]/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/s/[slug]/order/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/s/[slug]/order/[orderId]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/s/[slug]/order/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/s/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/s/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/s/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/coming-soon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/coming-soon">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/coming-soon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/login">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/automations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/automations">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/automations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/requests-digest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/requests-digest">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/requests-digest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/weekly-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/weekly-report">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/weekly-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/[slug]/customers.csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/[slug]/customers.csv">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/[slug]/customers.csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/[slug]/orders.csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/[slug]/orders.csv">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/[slug]/orders.csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/eat/photo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/eat/photo">> = Specific
  const handler = {} as typeof import("../../src/app/api/eat/photo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kitchen/[slug]/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kitchen/[slug]/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/kitchen/[slug]/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/loyalty/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/loyalty">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/loyalty/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/orders/[orderId]/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/orders/[orderId]/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/orders/[orderId]/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/orders/[orderId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/orders/[orderId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/orders/[orderId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/restaurants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/restaurants">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/restaurants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mobile/storefront/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mobile/storefront/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/mobile/storefront/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/twilio-sms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/twilio-sms">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/twilio-sms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/llms.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/llms.txt">> = Specific
  const handler = {} as typeof import("../../src/app/llms.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/[locale]/(admin)/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/admin">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(admin)/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(dashboard)/dashboard/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/dashboard/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(dashboard)/dashboard/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(marketing)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(marketing)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/(storefront)/s/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/s/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/(storefront)/s/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
